# Setup
title:               Tom Magnus
tagline:             'Technical writings and other fun stuff'
description:         'Welcome to my blog! This is mostly for exhibiting my technical writings at the moment. Enjoy your stay and feel free to contact me at " 
                      < a href="mailto:tom.magnus.94@gmail.com">tom.magnus.94@gmail.com< /a>'
url:                 'https://tom-the-magnus.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Tom Magnus
  url:               nothing.com
  email:             tom.magnus.94@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
